/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{vue,js,ts,jsx,tsx}",
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./app.vue"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#131b2e',
        'tertiary-container': '#6c748b',
        'on-surface': '#0b1c30',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'surface': '#f8f9ff',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'tertiary': '#545c72',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#cde5ff',
        'secondary': '#006399',
        'primary-container': '#008378',
        'on-tertiary-fixed-variant': '#3f465c',
        'secondary-fixed-dim': '#94ccff',
        'on-secondary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-secondary-container': '#004f7b',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eaf1ff',
        'background': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'primary-fixed-dim': '#6bd8cb',
        'on-error-container': '#93000a',
        'primary': '#00685f',
        'on-secondary-fixed-variant': '#004b74',
        'inverse-primary': '#6bd8cb',
        'tertiary-fixed-dim': '#bec6e0',
        'surface-container-low': '#eff4ff',
        'tertiary-fixed': '#dae2fd',
        'on-primary-fixed': '#00201d',
        'on-primary-container': '#f4fffc',
        'on-tertiary-container': '#fefcff',
        'on-primary-fixed-variant': '#005049',
        'surface-tint': '#006a61',
        'primary-fixed': '#89f5e7',
        'outline-variant': '#bcc9c6',
        'on-secondary-fixed': '#001d32',
        'on-surface-variant': '#3d4947',
        'outline': '#6d7a77',
        'secondary-container': '#7bc2ff',
        'surface-variant': '#d3e4fe',
        'error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        'sans': ['IBM Plex Sans Thai', 'IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '1.5', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
